package main

import (
	"fmt"
	"os"

	"github.com/jblew/osowiec-git-backup/app"
)

// GetAutogeneratedConfig is automatically generated file with project config
func GetConfig() (error, app.Config) {
	var conf = app.Config{}

	conf.RepositoriesListFile = os.Getenv("REPOSITORIES_LIST_FILE")
	if conf.RepositoriesListFile == "" {
		return fmt.Errorf("Missing env REPOSITORIES_LIST_FILE"), app.Config{}
	}

	conf.RepositoriesDir = os.Getenv("REPOSITORIES_DIR")
	if conf.RepositoriesDir == "" {
		conf.RepositoriesDir = "repos"
	}

	conf.SSHPrivateKeyPath = os.Getenv("SSH_PRIVATE_KEY_PATH")
	if conf.SSHPrivateKeyPath == "" {
		return fmt.Errorf("Missing env SSH_PRIVATE_KEY_PATH"), app.Config{}
	}

	conf.MonitoringEndpointPingSuccess = os.Getenv("MONITORING_ENDPOINT_PING_SUCCESS")
	conf.MonitoringEndpointPingFailure = os.Getenv("MONITORING_ENDPOINT_PING_FAILURE")
	conf.PrometheusPushGatewayURL = os.Getenv("PROMETHEUS_PUSHGATEWAY_URL")
	conf.PrometheusJobName = os.Getenv("PROMETHEUS_PUSHGATEWAY_JOBNAME")

	return nil, conf
}
